# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PKGroupManagement' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PKGroupManagement

  target 'PKGroupManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Google/SignIn'
